schema_version: 1

context:
  version: "1.12.1"

package:
  name: avrocpp
  version: ${{ version }}

source:
  url: https://github.com/apache/avro/archive/release-${{ version }}.tar.gz
  sha256: c915b531ed952c067a56810c8b0a87f4d8837079b45c73ebdd6065d8e0a54381
  patches:
    - patches/0002-Fix-linker-error-in-tests.patch

build:
  number: 2

requirements:
  build:
    - ninja
    - cmake <4
    - if: osx
      then: pkg-config
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != host_platform
      then:
        - snappy
        - liblzma-devel
        - zlib
        - libboost-devel

  host:
    - snappy
    - liblzma-devel
    - zlib
    - libboost-devel
    - fmt

tests:
  - script:
      - if: unix
        then:
          - test -f ${PREFIX}/lib/libavrocpp_s.a
          - test -f ${PREFIX}/lib/libavrocpp${SHLIB_EXT}
          - test -f ${PREFIX}/include/avro/Types.hh
      - if: win
        then:
          - if not exist %PREFIX%\\Library\\include\\avro\\Types.hh exit 1
          - if not exist %PREFIX%\\Library\\bin\\avrocpp.dll exit 1

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Avro is a serialization and RPC framework.
  homepage: https://avro.apache.org

extra:
  recipe-maintainers:
    - apmorton
    - mariusvniekerk
